### PR TITLE
Allow `psr/container:^2`

### PR DESCRIPTION
**Pull request by hannesvdvreken**
Only requires new minor version.

See hannesvdvreken/psr-container-v2-demonstrator#1 for an explanation.

### CODE REVIEW

**Comment by hannesvdvreken** [comment]
ping

**Comment by Ocramius** [comment]
This needs:

 * a rebase 
 * matching update of `composer.lock`

**Comment by hannesvdvreken** [comment]
Rebased.

Updated lockfile hash, but kept the locked versions the same.

Ping me when you want to run a `composer update`

**Review by Ocramius — APPROVED** [review]
LGTM 👍

**Comment by hannesvdvreken** [comment]
now on to https://github.com/mezzio/mezzio-csrf/pull/9

**Pull request merged**
